"""column added to User

Revision ID: f56fb1026622
Revises: 
Create Date: 2024-07-27 18:55:29.833337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56fb1026622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('position', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
